### ISSUE TITLE
Incorrect ResultCutPiece quantity on second StockPiece for case "pighetti_d"

### ISSUE THREAD

**Issue by lukepighetti** [jasonrhansen/cut-optimizer-2d#16]
On rev `e382e13` if I try to span 6 CutPieces over 2 StockPieces, I end up with 8 CutPieces

### Case

```rust
fn case_pighetti_d() {
    let case_name = "pighetti_d";

    let plywood = StockPiece {
        quantity: Some(2),
        length: 2440,
        width: 1220,
        pattern_direction: PatternDirection::ParallelToLength,
        price: 130,
    };

    let cut_piece_a = CutPiece {
        quantity: 6,
        external_id: Some(1),
        length: 814,
        width: 465,
        can_rotate: false,
        pattern_direction: PatternDirection::ParallelToLength,
    };

    let mut optimizer = Optimizer::new();
    optimizer.add_stock_piece(plywood);
    optimizer.add_cut_piece(cut_piece_a);
    optimizer.set_cut_width(2);

    optimizer.optimize_and_print(case_name);
}
```

### Expected Result
<img src="https://user-images.githubusercontent.com/666539/158381799-cb29bb9e-a14b-494d-8f93-3d008ddcd030.svg" width=200/> <img src="https://user-images.githubusercontent.com/666539/158382302-fea5131e-d0da-4bb3-9406-0a3a82e37cc9.svg" width=200/> 

### Actual Result
<img src="https://user-images.githubusercontent.com/666539/158381799-cb29bb9e-a14b-494d-8f93-3d008ddcd030.svg" width=200/> <img src="https://user-images.githubusercontent.com/666539/158381857-880c0545-5140-4ddb-9f5a-6977ebf9ab74.svg" width=200/>

**Comment by jasonrhansen** [comment]
Looks like there's still an issue with stock piece quantities. If I set the quantity to `None`, it gives the correct result.

**Comment by jasonrhansen** [comment]
@lukepighetti I figured out what was going on. Let me know if you notice any other strange behavior.

**Comment by lukepighetti** [comment]
On version `4.0.1` this is resolved, thanks!

<img src="https://user-images.githubusercontent.com/666539/158578718-d7fe19fe-6c6a-46ba-8c26-52a623be1138.svg" width=200/> <img src="https://user-images.githubusercontent.com/666539/158578751-f9cad41a-4557-40d5-867d-6d89852f38c1.svg" width=200/>
