### ISSUE TITLE
Result is non-deterministic for case "pighetti_d"

### ISSUE THREAD

**Issue by lukepighetti** [jasonrhansen/cut-optimizer-2d#18]
On version `4.0.1`, if I run the case `pighetti_d` described [here](https://github.com/jasonrhansen/cut-optimizer-2d/issues/16), half the time it will return Result A, otherwise Result B.

### Result A

<img src="https://user-images.githubusercontent.com/666539/158578718-d7fe19fe-6c6a-46ba-8c26-52a623be1138.svg" width=200/> <img src="https://user-images.githubusercontent.com/666539/158578751-f9cad41a-4557-40d5-867d-6d89852f38c1.svg" width=200/>

### Result B
<img src="https://user-images.githubusercontent.com/666539/158587646-62e9838b-b735-4194-a691-3159b93815ba.svg" width=200/> <img src="https://user-images.githubusercontent.com/666539/158587660-55d43ed5-72b2-4507-a5e2-ec384fb429c5.svg" width=200/>

**Comment by jasonrhansen** [comment]
This was caused by using `HashSet` for `unused_cut_pieces`, which gives different hashes for different runs.
