### ISSUE TITLE
Make Solution.price field public

### ISSUE THREAD

**Issue by lukepighetti** [jasonrhansen/cut-optimizer-2d#9]
Assuming the price is equal to the cost of consumed stock (cut piece + cutter kerf), it would be nice to make this field public so we can see the cost of the stock being cut.

This also opens up a conversation about creating something like a `CostMetrics` struct... perhaps with `stock_piece_cost` = `cut_piece_cost` + `cut_width_cost` + `waste_cost`

**Comment by jasonrhansen** [comment]
Would just adding the `price` field to `ResultStockPiece` get you what you want for now? I'm willing to do that.

Anything beyond that, I'm open to PRs.

**Comment by lukepighetti** [comment]
That handles my needs!

**Comment by jasonrhansen** [comment]
@lukepighetti  I'm going to close this issue, but I'm open to a more detailed proposal for you `CostMetrics` idea. If you'd like to pursue that further, please open a new issue that outlines what you're trying to accomplish.
